[project]
name = "hgere"
version = "0.1.0"
description = "A refactoring of the original HGERE code."
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "einops>=0.8.0",
    "setuptools>=75.6.0",
    "tensorboardx>=2.6.2.2",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
    "wandb>=0.19.9",
]

[tool.uv]
dev-dependencies = [
    "lint>=1.2.1",
    "ruff>=0.8.4",
    "tensorboard>=2.18.0",
]
