[project]
name = "hgere"
version = "0.1.0"
description = "A refactoring of the original HGERE code."
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "einops>=0.8.0",
    "setuptools>=75.6.0",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
    "wandb>=0.19.9",
    "transformers",
    "matplotlib>=3.9.0",
    "scikit-learn>=1.6.0",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "lint>=1.2.1",
    "ruff>=0.15.5",
    "pytest>=8.4.2",
]
[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv.sources]
torch = { index = "pytorch-cu128"}
torchvision = { index = "pytorch-cu128"}
torchaudio = { index = "pytorch-cu128"}
transformers = { path = "transformers", editable = true }
[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
