# Config for pipeline to process many documents

target_dir: pipeline/data/output/
pruner:
    threshold: 0.0005
    params:
        label_set: gsap
        model_dir: pipeline/models/pruner # this is the folder of the model
        data_dir: pipeline/data/input/
        output_dir: pipeline/data/output/ # this is the folder of the model
        test_file: docs.jsonl
        base_model_name_or_path: pretrained_models/scibert_scivocab_uncased
        model_type: bertspanmarkerpruner
        output_results:
        do_test: 
        per_gpu_eval_batch_size: 32
        max_seq_length: 256
        max_pair_length: 64
        max_mention_ori_length: 12
        topk_ratio: 100
        max_mentions_num: 30
        min_mentions_num: 30
        lminit:
        nocross:
        biaf_span:
        biaf_mode:  2
        biaf_factorize:
        span_hidden_size: 768
        rank: 768
        span_size: 256
        local_rank: -1

hgere:
  params:
    eval_test:
    label_set: gsap
    ner_prediction_dir: pipeline/data/output/
    test_file: docs.jsonl
    model_name_or_path: pretrained_models/scibert_scivocab_uncased
    output_dir: pipeline/models/hgere
    model_type: hyper
    do_lower_case:
    per_gpu_eval_batch_size: 32
    gradient_accumulation_steps: 1
    max_seq_length: 512 
    max_pair_length: 18
    eval_all_checkpoints:
    evaluate_during_training:
    factor_type: tersibcop
    factor_encoder: biaf
    ent_dim: 400
    rel_dim: 400
    mem_dim: 400
    layernorm:
    layernorm_1st:  
    attn_self:
