label_set: scinlp
model_dir: saves/scinlp/hgere/best_bs32_ep20
seeds:
    - 42
    - 43
    - 44
    - 45
    - 46
base_model_name_or_path: allenai/scibert_scivocab_uncased
model_type: hyper
do_lower_case: true
no_sym: true
per_gpu_eval_batch_size: 32
max_ents: 18
max_seq_length: 512 # 512!
factor_type: tersibcop # tersibcop # ternary not run yet
factor_encoder: biaf
ent_dim: 400
rel_dim: 400
mem_dim: 400
ent_repr: mix
n_iter: 3
layernorm: true
layernorm_1st: true
attn_self: true
ner_focal_loss: false
re_focal_loss: false

# Data
## Pruner predictions used as NER candidates input to HGERE
ner_prediction_dir: saves/scinlp/pruner/best
#data_dir: datasets/gsap-ere

# Optimisation
train_params:
    num_train_epochs: 20
    pre_filter_params:
        method: threshold
        value: 0.015
    learning_rate: 1e-5
    learning_rate_cls: 1e-4
    per_gpu_train_batch_size: 32
    # W&B
    log_wandb: true
    project_name: scinlp-hgere
    wandb_entity: ottowg-gesis7279
    # data
    train_file: ent_pred_trai.json
    dev_file: ent_pred_de.json
    test_file: ent_pred_tes.json
    save_results: true
    eval_train: true
    eval_test: true
    shuffle: false
    preload_dataset: false
    n_workers: 16
    do_train: true
    eval_epochs: 2
    gradient_accumulation_steps: 1
    adam_epsilon: 1e-8
    weight_decay: 0.1
    warmup_ratio: 0.1 # dafault 0.1
    fp16: true
    local_rank: -1
    # Loss
    loss_re_weight_alpha: 0.5 # (1 - alpha) * loss_ner + alpha * loss_re
    # Evaluation
    evaluate_during_training: true
    eval_all_checkpoints: true
    overwrite_output_dir: true
