label_set: gsap
model_dir: saves/gsap/HGERE/gefieder
base_model_name_or_path: pretrained_models/scibert_scivocab_uncased
model_type: hyper
do_lower_case: true
no_sym: false
per_gpu_eval_batch_size: 32
max_seq_length: 512
max_pair_length: 18
factor_type: ternary # tersibcop # ternary not run yet
factor_encoder: biaf
ent_dim: 400
rel_dim: 400
mem_dim: 400
ent_repr: mix
n_iter: 3
layernorm: true
layernorm_1st: true

# Data
## Pruner predictions used as NER candidates input to HGERE
ner_prediction_dir: saves/gsap/pruner/pelikan
#data_dir: datasets/gsap-ere

# Optimisation
train_params:
    project_name: gsap-rel-hgere
    run_name: gefieder
    train_file: ent_pred_train.json
    dev_file: ent_pred_dev.json
    test_file: ent_pred_test.json
    save_results: true
    eval_train: true
    eval_test: true
    seed: 45
    shuffle: true # not tested yet
    preload_dataset: false # not tested yet
    pre_filter_params:
        method: "threshold"
        value: 0.1
    do_train: true
    learning_rate: 1e-5
    learning_rate_cls: 1e-5
    num_train_epochs: 8
    eval_epochs: 1
    per_gpu_train_batch_size: 32
    gradient_accumulation_steps: 1
    adam_epsilon: 1e-8
    fp16: true
    local_rank: -1
    # Loss
    loss_re_weight_alpha: 0.9 # (1 - alpha) * loss_ner + alpha * loss_re
    ner_focal_loss: true
    re_focal_loss: true
    # Model flags
    attn_self: true
    # Evaluation
    evaluate_during_training: true
    eval_all_checkpoints: true
    overwrite_output_dir: true
    # W&B
    log_wandb: true
